all: simple-copy

simple-copy: simple-copy.o
	g++ simple-copy.o -o simple-copy

simple-copy.o: simple-copy.cpp
	g++ -c simple-copy.cpp -o simple-copy.o

run: simple-copy
	./simple-copy source-file destination-file

clean:
	rm -f *.o simple-copy destination-file

.PHONY: all clean run
